### GET request to example server
POST http://localhost:8080/auth/sing-up
Content-Type: application/json

{
  "name": "vitalu",
  "email": "example123@example.com",
  "password": "yourpassword123"
}

###

GET http://localhost:8080/files/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzI4MTU5NjAsImlhdCI6MTczMjgxNTA2MCwic3ViIjoiMSJ9.j48GgdfYd3VbfmPAlR6eIFj_nIQi18qC3oFXitdP_hU

