env: "local"
http_server:
  address: "localhost:8080"
  write_timeout: 4s
  read_timeout: 4s
  idle_timeout: 60s
postgres_db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "mysecretpassword"